name: house_sales_prediction
channels:
  - defaults
dependencies:
  - cloudpickle=0.6.1
  - python=3.6
  - numpy=1.14.3
  - pandas=0.22.0
  - scikit-learn=0.19.1
  - seaborn=0.9
  - keras=2.1.5
  - tensorflow==1.7.0
  - pip
  - pip:
    - mlflow
